apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: petclinic

  template:
    metadata:
      labels:
        app: petclinic

    spec:
      containers:
        - name: petclinic

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          env:

            - name: SPRING_PROFILES_ACTIVE
              value: postgres

            - name: POSTGRES_URL
              value: "jdbc:postgresql://{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}"

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: petclinic-db
                  key: POSTGRES_USER

            - name: POSTGRES_PASS
              valueFrom:
                secretKeyRef:
                  name: petclinic-db
                  key: POSTGRES_PASS

          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 20