global:
  domain: "${traefik_nlb_dns}"

configs:
  params:
    server.insecure: true

server:
  replicas: 1

  service:
    type: ClusterIP

  ingress:
    enabled: true
    controller: generic
    ingressClassName: traefik

    hostname: "${traefik_nlb_dns}"

    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: web

    path: /
    pathType: Prefix
    tls: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

redis:
  enabled: true